In [1]:
import torch
import numpy as np

In [2]:
indices = torch.tensor([1, 3, 5])
num_categories = 10

# Convert indices to one-hot
one_hot = torch.nn.functional.one_hot(indices, num_categories)

# Since you want a single tensor representing all indices in a "sparse" way,
# you sum along the first dimension
sparse_one_hot = one_hot.sum(dim=0)

print(sparse_one_hot)

tensor([0, 1, 0, 1, 0, 1, 0, 0, 0, 0])


In [ ]:
a = torch.nn.Embedding(10,30)
a.weight = torch.nn.Parameter(torch.tensor(1.0))

In [ ]:
b = torch.from_numpy(np.ones((64, 256, 20))).long()

In [ ]:
a(b).shape

In [33]:
#4 batches, 3 blocks, 2 classes 
a = np.arange(0,4*3*2).reshape((4,3,2))

In [34]:
a.

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [35]:
a.reshape(-1, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])